const nodemailer = require("nodemailer");

function sendEmail({
  song_name,
  artist,
  youtube_title,
  youtube_views,
  spotify_title,
  spotify_streams,
  shazam_count,
  chartex_stats,
  spotontrack_image_base64,
  mediaforest_image_base64,
  youtube_diff,
  youtube_daily_avg,
  youtube_weekly_avg,
  spotify_diff,
  spotify_daily_avg,
  spotify_weekly_avg,
  shazam_title,
  shazam_diff,
  shazam_daily_avg,
  shazam_weekly_avg,
  tiktok_csv_base64
}) {
    const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
            user: process.env.MAIL_USER,
            pass: process.env.MAIL_PASS
        }
    });

    const html = `
    <div style="font-family: Arial; padding: 20px;">
      <h2 style="color:#4a90e2;">🎵 Track Analysis Report</h2>
      <p><strong>Song:</strong> ${song_name}<br/>
         <strong>Artist:</strong> ${artist}</p>
    
      <h3>🎧 DSP Performance</h3>
    
      <h4>YouTube</h4>
      <p>
        <strong>Title:</strong> ${youtube_title}<br/>
        <strong>Views:</strong> ${youtube_views}<br/>
        <strong>Difference since last check:</strong> ${youtube_diff || "-"}<br/>
        <strong>Daily average (today):</strong> ${youtube_daily_avg || "-"}<br/>
        <strong>Weekly average (7d):</strong> ${youtube_weekly_avg || "-"}
      </p>
    
      <h4>Spotify</h4>
      <p>
        <strong>Title:</strong> ${spotify_title}<br/>
        <strong>Streams:</strong> ${spotify_streams}<br/>
        <strong>Difference since last check:</strong> ${spotify_diff || "-"}<br/>
        <strong>Daily average (today):</strong> ${spotify_daily_avg || "-"}<br/>
        <strong>Weekly average (7d):</strong> ${spotify_weekly_avg || "-"}
      </p>
    
      <h4>Shazam</h4>
      <p>
        <strong>Title:</strong> ${shazam_title}<br/>
        <strong>Count:</strong> ${shazam_count}<br/>
        <strong>Difference since last check:</strong> ${shazam_diff || "-"}<br/>
        <strong>Daily average (today):</strong> ${shazam_daily_avg || "-"}<br/>
        <strong>Weekly average (7d):</strong> ${shazam_weekly_avg || "-"}
      </p>
    
      <h4>Spotontrack</h4>
      <img src="cid:spotontrack" style="max-width:600px; border-radius: 8px;" />
    
      <h3>📱 TikTok Performance</h3>
      <p>${chartex_stats}</p>
      <p>Vezi CSV-ul atașat în acest email.</p>
    
      <h3>📻 Radio Performance</h3>
      <img src="cid:mediaforest" style="max-width:600px; border-radius: 8px;" />
    
      <p style="margin-top:30px;color:#999;font-size:12px;">Generated by SongScape AI</p>
    </div>
    `;


    return transporter.sendMail({
        from: `"SongScape AI" <${process.env.MAIL_USER}>`,
        to: process.env.MAIL_TO,
        subject: `${song_name} Analysis Report`,
        html,
        attachments: [
            {
                filename: "spotontrack.png",
                content: Buffer.from(spotontrack_image_base64, 'base64'),
                cid: "spotontrack"
            },
            {
                filename: "mediaforest.png",
                content: Buffer.from(mediaforest_image_base64, 'base64'),
                cid: "mediaforest"
            },
            {
                filename: "TikTokPerformance.csv",
                content: Buffer.from(tiktok_csv_base64, 'base64'),
                contentType: "text/csv"
            }
        ]
    });
}

module.exports = { sendEmail };
